language: android
android:
  components:
    - build-tools-19.0.3

branches:
  only:
    - travis

notifications:
  email: false

before_install:

  # for gradle output style
  #- export TERM=dumb

  # environment info
  - ./gradlew -v
  - uname -a

# Let's try to build...
#install: ./gradlew clean build

#script: ./gradlew check


